### ISSUE TITLE
What does this line of code do ? 

### ISSUE THREAD

**Issue by ROHROCK** [EagleFury2607/LP1-Programs#1]
I am confused about the condition of termination of for loop 

https://github.com/EagleFury2607/LP1-Programs/blob/0bf80313a06f0995e45f83b5520b86d4a5776fb7/HPC/Cuda/sum_updated.cu#L5

**Comment by EagleFury2607** [comment]
When we call the kernel function --
      sum<<<2,50>>>();
     total threads here are 2*50 =100 and our data is also 100 numbers
So each thread is assigned to each number and it gives sum
If we increase number of threads there is no problem as we are using condition --
      if(i<100)
So it will give correct result 
But if we decrease number of threads for example --
     sum<<<2,25>>>();
in this case it will process only 50 numbers out of 100
in this case each thread should run two times 
blockDim.x*gridDim.x gives number of threads 25*2
so dividing it by number of elements to be processed will give how many times each thread should run or how many elements each thread should process.
Therefore, 100/(blockDim.x*gridDim.x) = 100/(25*2) = 2
So each thread should execute two elements.
for loop will run two times for each thread 
1st time for ith element
2nd time for i + 50 th element in this case

**Comment by ROHROCK** [comment]
Okay thanx , I got it !
