### ISSUE TITLE
What does this line of for loop condition do ?

### ISSUE THREAD

**Issue by ROHROCK** [EagleFury2607/LP1-Programs#2]
Correct me if I am wrong . From my understanding the loop initially will just start with 0 since threadIdx is 0 , and increment with the by 2 (blockDim) in this program , since there are 2 blocks of 50 threads each . 

https://github.com/EagleFury2607/LP1-Programs/blob/653d560a43c211398a1c43062df72e8db246a1d3/HPC/Cuda/parallel_min.cu#L9

But this loop will be running on each thread in the GPU , so whats the loop used for ? Is is for **reduction** operation for each block ?

**Comment by EagleFury2607** [comment]
Yes, let's suppose there are 100 elements in data with 25 threads 
then for loop for i = 0 will run as
i = 0,25,50,75 so that even if threads are less than data all data elements will be processed

**Comment by ROHROCK** [comment]
okay how many threads and blocks did u consider for above example ?

**Comment by EagleFury2607** [comment]
50 threads per block and 2 blocks
therefore, 100 threads
